# Generated by Django 6.0.1 on 2026-01-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_entrega', models.DateTimeField()),
                ('mensaje_pastel', models.TextField(blank=True)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('decoraciones', models.ManyToManyField(blank=True, to='pedidos.decoracion')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.formapastel')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.sabor')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPastel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.formapastel')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.sabor')),
            ],
        ),
    ]
