# Generated by Django 6.0.1 on 2026-01-10 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_decoracion_pedido_preciopastel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='decoraciones',
        ),
        migrations.RemoveField(
            model_name='preciopastel',
            name='forma',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma',
            field=models.CharField(choices=[('circular', 'Circular'), ('cuadrada', 'Cuadrada'), ('plancha', 'Planchas')], default='circular', max_length=20),
        ),
        migrations.RemoveField(
            model_name='preciopastel',
            name='sabor',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(choices=[('vainilla', 'Vainilla'), ('chocolate', 'Chocolate'), ('marmoleado_naranja', 'Marmoleado Naranja'), ('marmoleado_redvelvet', 'Marmoleado Red Velvet'), ('marmoleado_banano', 'Marmoleado Banano')], default='vainilla', max_length=30),
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mensaje_pastel',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
        migrations.AddField(
            model_name='pedido',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='base_entrega',
            field=models.CharField(choices=[('plana', 'Plana'), ('alta', 'Alta'), ('sencilla', 'Sencilla')], default='plana', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_diseño',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='celular',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='diseño',
            field=models.CharField(choices=[('perlas', 'Perlas'), ('papel_dorado', 'Papel dorado'), ('papel_plateado', 'Papel plateado'), ('flores_comestibles', 'Flores comestibles'), ('flores_reales', 'Flores reales')], default='perlas', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='impresion_arroz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='impresion_foto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porciones',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='responsable',
            field=models.CharField(default='Sin responsable', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('relleno', 'Relleno'), ('humedo', 'Húmedo'), ('especial', 'Especial')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Decoracion',
        ),
        migrations.DeleteModel(
            name='FormaPastel',
        ),
        migrations.DeleteModel(
            name='PrecioPastel',
        ),
        migrations.DeleteModel(
            name='Sabor',
        ),
    ]
