# Generated by Django 6.0.1 on 2026-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_diseño',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='diseño',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='porciones',
        ),
        migrations.AddField(
            model_name='pedido',
            name='flores_comestibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='flores_reales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='perlas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='base_entrega',
            field=models.CharField(blank=True, choices=[('sencilla', 'Sencilla'), ('plana', 'Plana'), ('alta', 'Alta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma',
            field=models.CharField(choices=[('circular_0', 'Circular Nº0 (4 pers.)'), ('circular_1', 'Circular Nº1 (8 pers.)'), ('circular_2', 'Circular Nº2 (12 pers.)'), ('circular_3', 'Circular Nº3 (18 pers.)'), ('circular_4', 'Circular Nº4 (25 pers.)'), ('cuadrada_1', 'Cuadrada Nº1 (12 pers.)'), ('cuadrada_2', 'Cuadrada Nº2 (18 pers.)'), ('cuadrada_3', 'Cuadrada Nº3 (25 pers.)'), ('plancha_1_2', 'Media Plancha (30 pers.)'), ('plancha_1', 'Plancha (60 pers.)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(blank=True, choices=[('vainilla', 'Vainilla'), ('chocolate', 'Chocolate'), ('marmoleado', 'Marmoleado'), ('naranja', 'Naranja'), ('red_velvet', 'Red Velvet'), ('banano', 'Banano')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('relleno', 'Relleno'), ('humedo', 'Húmedo'), ('especial', 'Especial')], max_length=20),
        ),
    ]
