# Generated by Django 6.0.1 on 2026-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_cantidad_diseño_remove_pedido_diseño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='papel_dorado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='papel_plateado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='base_entrega',
            field=models.CharField(blank=True, choices=[('plana', 'Plana'), ('alta', 'Alta'), ('sencilla', 'Sencilla')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma',
            field=models.CharField(choices=[('circular_0', 'N#0 Circular (4 pers.)'), ('circular_1', 'N#1 Circular (8 pers.)'), ('circular_2', 'N#2 Circular (12 pers.)'), ('circular_3', 'N#3 Circular (18 pers.)'), ('circular_4', 'N#4 Circular (25 pers.)'), ('cuadrada_1', 'N#1 Cuadrada (12 pers.)'), ('cuadrada_2', 'N#2 Cuadrada (18 pers.)'), ('cuadrada_3', 'N#3 Cuadrada (25 pers.)'), ('plancha_1_2', 'Media Plancha (30 pers.)'), ('plancha_1', 'Plancha (60 pers.)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='impresion_arroz',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(blank=True, choices=[('mora', 'Mora'), ('piña', 'Piña'), ('guayaba', 'Guayaba'), ('crema_pastelera', 'Crema Pastelera'), ('chocolate', 'Chocolate'), ('fresa', 'Fresa'), ('durazno', 'Durazno'), ('cereza', 'Cereza'), ('manjar', 'Manjar')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('relleno_tradicional', 'Relleno Tradicional'), ('relleno_especial', 'Relleno Especial'), ('humedo', 'Húmedo'), ('especial', 'Especial')], max_length=30),
        ),
    ]
