# Generated by Django 6.0.1 on 2026-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_precioformatipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('relleno', 'Relleno')], max_length=30),
        ),
    ]
