# Generated by Django 6.0.1 on 2026-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(blank=True, choices=[('', '---------')], max_length=30, null=True),
        ),
    ]
