# Generated by Django 6.0.1 on 2026-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioFormaTipoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PrecioFormaTipo',
        ),
    ]
