# Generated by Django 6.0.1 on 2026-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_precioformatiposabor_delete_precioformatipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dibujo_mano',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=20),
        ),
    ]
