# Generated by Django 6.0.1 on 2026-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_dibujo_mano_pedido_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sabor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
