# Generated by Django 6.0.1 on 2026-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedido_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
