# Generated by Django 6.0.1 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
