# Generated by Django 6.0.1 on 2026-02-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_fotos/'),
        ),
    ]
