# Generated by Django 6.0.1 on 2026-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedido_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='impresion_arroz',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
