# Generated by Django 6.0.1 on 2026-02-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_pedido_impresion_arroz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='dificultad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='diseno_torta',
            field=models.CharField(choices=[('facil', 'Diseño Fácil'), ('medio', 'Diseño Medio'), ('dificil', 'Diseño Difícil')], default='facil', max_length=20, verbose_name='Diseño de torta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='impresion_arroz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
