# Generated by Django 6.0.1 on 2026-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_remove_pedido_dificultad_pedido_diseno_torta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_pedido',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de pedido'),
        ),
    ]
