# Generated by Django 6.0.1 on 2026-03-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_remove_pedido_fecha_remove_pedido_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_normal',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Normal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_relleno',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Relleno'),
        ),
    ]
